### ISSUE TITLE
Spawners changing to pigs when placed

### ISSUE THREAD

**Issue by krustymk** [timbru31/SilkSpawners#51]
Spigot 1.11 with SilkSpawners build off spigot page
Updated Spigot tonight and got Build #374
Same issue still 
also Build #374 doesnt report version number when /ss help is called (like the changes say it will)

**Comment by timbru31** [comment]
You have to delete the localization.yml file in order to get the updated string which supports version placeholder.

I need a reproducible how to, to be able to solve the issue. In 99% of the cases it's another plugins error, so please try to disable them one by one and if you have found the culprit, please report it.

**Comment by timbru31** [comment]
Closing due to lack of response. If the error still occurs, please create a new ticket and follow the issue template

**Comment by krustymk** [comment]
Apologies, forgot all about this. Turned out to be another plugin that could manage spawners (CMI Content Management Interface), the functionality was added on an update and i didnt spot it. Disabled it in their config to solve

**Comment by timbru31** [comment]
Thanks for the update - it's always quite helpful to know which plugins conflict. Glad you solved it.
